# -*- coding: utf-8 -*-
"""Restaurant_Reviews_SVM_classifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QO2GxQNYNZzovmbMZdAIf72df5ShiDWl
"""

import numpy as np
import pandas as pd

df=pd.read_csv("/content/drive/MyDrive/Restaurant_Reviews.tsv",delimiter='\t',quoting=3)

df.shape,df.columns

df.tail()

import re
import nltk

nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

corpus = []

for i in range(0, 1000):
	review = re.sub('[^a-zA-Z]', repl=' ',string= df['Review'][i])
	review = review.lower()
	review = review.split()
	ps = PorterStemmer()
	review = [ps.stem(word) for word in review
				if not word in set(stopwords.words('english'))]
	review = ' '.join(review)
	corpus.append(review)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['Review'], df['Liked'], test_size=0.2, random_state=42)

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_features=1000)  # max_features
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

from sklearn.svm import SVC
svm_classifier = SVC(kernel='linear', C=1.0)
svm_classifier.fit(X_train_tfidf, y_train)

y_pred = svm_classifier.predict(X_test_tfidf)
y_pred

from sklearn.metrics import accuracy_score, classification_report
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print("Classification Report:\n", report)

#for positive rating
from sklearn.metrics import precision_score, recall_score

# Calculating precision and recall
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)

# Printing the results
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Calculating the confusion matrix
cm = confusion_matrix(y_test, y_pred)

class_names = ['Negative', 'Positive']

# Creating a heatmap of the confusion matrix
plt.figure(figsize=(8, 6))
sns.set(font_scale=1.2)  # Adjust font size for better readability
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)

# Adding labels and a title
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.title('Confusion Matrix')

# Displaying the plot
plt.show()

from sklearn.manifold import TSNE

# Assuming you have already performed sentiment analysis and have TF-IDF vectors
# X_train_tfidf and X_test_tfidf from the previous example

# Combining the training and test sets for visualization
X_combined = np.vstack((X_train_tfidf.toarray(), X_test_tfidf.toarray()))
y_combined = np.hstack((y_train, y_test))

# Performing t-SNE dimensionality reduction
tsne = TSNE(n_components=2, random_state=42)
X_tsne = tsne.fit_transform(X_combined)
# Plotting the results
plt.figure(figsize=(8, 6))
scatter = plt.scatter(X_tsne[:, 0], X_tsne[:, 1], c=y_combined, cmap='coolwarm')
plt.colorbar(scatter, label='Sentiment (0: Negative, 1: Positive)')
plt.title('t-SNE Visualization of Sentiment Analysis Results SVC')
plt.show()

score1=accuracy_score(y_test,y_pred)
score2=precision_score(y_test,y_pred)
score3=recall_score(y_test,y_pred)
cm = confusion_matrix(y_test, y_pred)
# Printing the results
print("Accuracy Score is :{}%".format(round(score1*100,2)))
print("Precision Score is :{}%".format(round(score2*100,2)))
print("Recall Score is :{}%".format(round(score3*100,2)))
cm